server:
  port: 8089
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.31.10:3306/test
      username: admin
      password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml